git-debimport systemd_215-14.debian.tar.xz

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -18,12 +18,17 @@ CONFFLAGS = \
 	--with-firmware-path=/lib/firmware \
 	--with-debug-shell=/bin/bash \
 	--with-telinit=/lib/sysvinit/telinit \
-	--enable-tcpwrap \
 	--disable-coredump \
 	--disable-efi \
 	--disable-myhostname \
 	--disable-vconsole \
-	--disable-silent-rules
+	--disable-microhttpd \
+	--disable-sysusers \
+	--disable-silent-rules \
+	--with-ntp-servers="0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org"  \
+	--with-system-uid-max=999 \
+	--with-system-gid-max=999
+
 ifeq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
 CONFFLAGS += --enable-libcryptsetup
 endif
@@ -32,10 +37,14 @@ CONFFLAGS_deb = \
 	--enable-selinux \
 	--enable-introspection \
 	--enable-gtk-doc \
+	--enable-compat-libs \
 	PYTHON=python3 \
 	$(NULL)
 
 CONFFLAGS_udeb = \
+	--disable-libcryptsetup \
+	--disable-pam \
+	--disable-audit \
 	--disable-selinux \
 	--disable-smack \
 	--disable-ima \
@@ -52,10 +61,16 @@ CONFFLAGS_udeb = \
 	--disable-machined \
 	--disable-hostnamed \
 	--disable-timedated \
+	--disable-networkd \
+	--disable-timesyncd \
 	--disable-localed \
+	--disable-resolved \
 	--disable-polkit \
 	--disable-acl \
+	--disable-gcrypt \
 	--disable-gudev \
+	--disable-rfkill \
+	--disable-multi-seat-x \
 	--disable-manpages \
 	--without-python
 
@@ -81,6 +96,12 @@ override_dh_auto_clean:
 	rm -rf debian/install/
 	# remove pre-generated man pages so they are rebuilt
 	rm -f man/*.[13578]
+	# remove pre-generated rules and unit files so they are rebuilt
+	rm -f rules/99-systemd.rules \
+		units/emergency.service \
+		units/systemd-udevd.service \
+		units/systemd-udev-settle.service \
+		units/systemd-udev-trigger.service
 	# remove Python byte code files
 	rm -f *.pyc
 
@@ -99,6 +120,19 @@ override_dh_install:
 	rm -rf debian/install/*/etc/kernel/
 	rm -f debian/install/*/usr/lib/sysctl.d/50-default.conf
 	find debian/install/ -name '*.la' -delete
+	# remove files related to factory-reset feature
+	find debian/install/ \( -name 'systemd-update-done*' -o \
+		-name systemd-journal-catalog-update.service -o \
+		-name systemd-udev-hwdb-update.service -o \
+		-name ldconfig.service -o \
+		-name etc.conf \) -delete
+	# remove .so for deprecated compatibility libraries
+	rm -f debian/install/*/usr/lib/*/libsystemd-daemon.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-login.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-id128.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-journal.so
+	# remove symlinks enabling default-on services
+	rm -rf debian/install/*/etc/systemd/system/*.target.wants/
 	dh_install -pudev-udeb -plibudev1-udeb --sourcedir=debian/install/udeb
 	dh_install $(BOOTSTRAP_DH_FLAGS) -Nudev-udeb -Nlibudev1-udeb --sourcedir=debian/install/deb --fail-missing
 	# install some files manually, --sourcedir makes that necessary
@@ -149,14 +183,31 @@ override_dh_install:
 		debian/systemd/lib/lsb/init-functions.d/40-systemd
 	install --mode=644 debian/tmpfiles.d/debian.conf \
 		debian/systemd/usr/lib/tmpfiles.d/
-	install --mode=644 debian/debian-fixup.service debian/ifup@.service \
-		debian/units/run-lock.mount debian/units/run-user.mount \
+	install --mode=644 debian/debian-fixup.service \
+		debian/ifup@.service \
+		debian/extra/getty-static.service \
+		debian/extra/hwclock-save.service \
+		debian/extra/systemd-setup-dgram-qlen.service \
 		debian/systemd/lib/systemd/system/
+	install -D --mode=644 debian/extra/network-pre.conf \
+		debian/systemd/lib/systemd/system/networking.service.d/network-pre.conf
 	install --mode=644 debian/extra/udev-finish.service \
 		debian/udev/lib/systemd/system/
 	ln -s ../udev-finish.service debian/udev/lib/systemd/system/sysinit.target.wants/
 	install --mode=755 debian/debian-fixup \
 		debian/systemd/lib/systemd/
+	# Make sure the runlevel services are known by systemd so their targets
+	# get launches. See https://bugzilla.redhat.com/show_bug.cgi?id=1002806
+	for t in poweroff rescue multi-user graphical reboot; do \
+		mkdir -p debian/systemd/lib/systemd/system/$${t}.target.wants;\
+		ln -s ../systemd-update-utmp-runlevel.service \
+			debian/systemd/lib/systemd/system/$${t}.target.wants ;\
+	done
+	# man files for example code in /usr/share/doc
+	mkdir -p debian/systemd/usr/share/man/man3/
+	mv debian/libsystemd-dev/usr/share/man/man3/sd-readahead.3 \
+		debian/libsystemd-dev/usr/share/man/man3/sd_readahead.3 \
+		debian/systemd/usr/share/man/man3/
 	install --mode=755 debian/systemd-logind-launch \
 		debian/systemd/lib/systemd/
 	# remove duplicates
@@ -188,13 +239,12 @@ endif
 	rm debian/udev/lib/udev/rules.d/73-seat-late.rules
 	rm debian/udev/lib/udev/rules.d/71-seat.rules
 	rm debian/udev/lib/udev/rules.d/99-systemd.rules
-	# files shipped by libsystemd-*-dev
-	find debian/libsystemd-*-dev -name "*.3" -exec sh -c \
-		'rm debian/systemd/usr/share/man/man3/$$(basename {})' \;
 
 # use symlinked doc directories as the old udev package did
 override_dh_installdocs:
 	dh_installdocs -pudev -plibudev-dev --link-doc=libudev1
+	# we have to manually install udev's README for the above
+	install -D --mode 644 debian/udev.README.Debian debian/libudev1/usr/share/doc/libudev1/README.Debian
 	dh_installdocs -pgir1.2-gudev-1.0 -plibgudev-1.0-dev --link-doc=libgudev-1.0-0
 	dh_installdocs --remaining-packages
 
@@ -227,9 +277,20 @@ override_dh_autoreconf:
 override_dh_strip:
 	dh_strip --dbg-package=systemd-dbg
 
+override_dh_auto_test:
+ifeq (, $(findstring nocheck, $(DEB_BUILD_OPTIONS)))
+	# some tests hang under fakeroot, so disable fakeroot
+	echo "01234567890123456789012345678901" > build-deb/machine-id
+	env -u LD_PRELOAD SYSTEMD_MACHINE_ID_PATH=$(CURDIR)/build-deb/machine-id \
+		make -C build-deb check || ( \
+		cd build-deb; \
+		for f in test-*.log; do echo "==== $$f ===="; cat $$f; done; \
+		exit 0; )  # replace with 1 to make failures fatal
+endif
+
 %:
 ifeq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
-	dh $@ --with autoreconf,gir,python3
+	dh $@ --with autoreconf,gir,python3 --parallel
 else
 	dh $@ --with autoreconf,python3 $(BOOTSTRAP_DH_FLAGS)
 endif
